In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import datetime as dt
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df  =  pd.read_csv("flow_controller_headcount_defect.csv")
df.head(20)

,fc,shift,day,process_path,process,interval_start_local,interval_end_local,dow,quarter,alert_trigger_time_local,...,actual_rate,actual,planned,dev_percentage,plannedrate,planned_deviation,predicted_deviation,rate_deviation,rate_defect_type,deviation_type
0,NCL2,Night,2026-02-14T00:00:00.000Z,PICK_MANUAL,PICK,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,NaN,...,47.983164,NaN,NaN,NaN,100.0,52.016836,82.739869,52.016836,under_performance,override_better
1,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM2,PACK,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,NaN,...,458.315428,NaN,NaN,NaN,231.0,-98.404947,-38.883463,-98.404947,over_performance,override_worse
2,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM,PACK,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,2026-02-15T04:29:27.000Z,...,454.370016,4.0,2.0,100.00%,350.0,-29.820005,-5.422278,-29.820005,over_performance,override_worse
3,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAMMIX,PACK,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,NaN,...,307.107182,NaN,NaN,NaN,266.0,-15.453828,-28.496729,-15.453828,over_performance,override_better
4,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1INDUCT,INDUCT,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,NaN,...,1484.747996,NaN,NaN,NaN,1235.0,-20.222510,-12.141087,-20.222510,over_performance,override_worse
5,NCL2,Night,2026-02-14T00:00:00.000Z,PPPICKTOREBIN3,PACK,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,02:00 - 05:00,NaN,...,155.080250,NaN,NaN,NaN,203.0,23.605788,6.578163,23.605788,under_performance,override_worse
6,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1PACK,PACK,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,23:30 - 01:30,NaN,...,306.562894,NaN,NaN,NaN,263.0,-16.563838,-12.294101,-16.563838,over_performance,override_worse
7,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAMMIX,PACK,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,23:30 - 01:30,NaN,...,325.107965,NaN,NaN,NaN,272.0,-19.524987,-30.043186,-19.524987,over_performance,override_better
8,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM2,PACK,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,23:30 - 01:30,NaN,...,434.794451,NaN,NaN,NaN,248.0,-75.320343,-32.964664,-75.320343,over_performance,override_worse
9,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM,PACK,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,23:30 - 01:30,NaN,...,482.205759,NaN,NaN,NaN,375.0,-28.588202,-10.597651,-28.588202,over_performance,override_worse
10,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1INDUCT,INDUCT,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,23:30 - 01:30,NaN,...,1591.983518,NaN,NaN,NaN,1261.0,-26.247702,-20.240447,-26.247702,over_performance,override_worse
11,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM,PACK,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,22:00 - 23:30,NaN,...,586.325831,NaN,NaN,NaN,485.0,-20.891924,-4.888342,-20.891924,over_performance,override_worse
12,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1INDUCT,INDUCT,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,22:00 - 23:30,NaN,...,1500.522809,NaN,NaN,NaN,1261.0,-18.994672,-7.873674,-18.994672,over_performance,override_worse
13,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1PACK,PACK,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,22:00 - 23:30,NaN,...,337.638763,NaN,NaN,NaN,263.0,-28.379758,-7.528268,-28.379758,over_performance,override_worse
14,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAMMIX,PACK,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,22:00 - 23:30,NaN,...,343.379357,NaN,NaN,NaN,272.0,-26.242411,-14.079521,-26.242411,over_performance,override_worse
15,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM2,PACK,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,22:00 - 23:30,NaN,...,477.713508,NaN,NaN,NaN,320.0,-49.285471,-21.555600,-49.285471,over_performance,override_worse
16,NCL2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM2,PACK,2026-02-14T19:30:00.000Z,2026-02-14T21:30:00.000Z,Sat,19:30 - 21:30,NaN,...,441.772260,NaN,NaN,NaN,330.0,-33.870382,-20.046810,-33.870382,over_performance,override_worse
17,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1PACK,PACK,2026-02-14T19:30:00.000Z,2026-02-14T21:30:00.000Z,Sat,19:30 - 21:30,NaN,...,336.950407,NaN,NaN,NaN,280.0,-20.339431,-12.316802,-20.339431,over_performance,override_worse
18,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1INDUCT,INDUCT,2026-02-14T19:30:00.000Z,2026-02-14T21:30:00.000Z,Sat,19:30 - 21:30,NaN,...,1524.073358,NaN,NaN,NaN,1300.0,-17.236412,-9.566740,-17.236412,over_performance,override_worse
19,NCL2,Night,2026-02-14T00:00:00.000Z,PPAFE1PACK,PACK,2026-02-14T18:45:00.000Z,2026-02-14T19:30:00.000Z,Sat,18:45 - 19:30,NaN,...,343.903969,NaN,NaN,NaN,280.0,-22.822846,-18.997913,-22.822846,over_performance,override_worse

In [3]:
df.dtypes

fc                           object
shift                        object
day                          object
process_path                 object
process                      object
interval_start_local         object
interval_end_local           object
dow                          object
quarter                      object
alert_trigger_time_local     object
week                          int64
year_number_sun               int64
staffing_defect_type         object
predictedrate                 int64
actual_rate                 float64
actual                      float64
planned                     float64
dev_percentage               object
plannedrate                 float64
planned_deviation           float64
predicted_deviation         float64
rate_deviation              float64
rate_defect_type             object
deviation_type               object
dtype: object

In [4]:
df_needed  =  df[['shift','day','process_path','interval_start_local','interval_end_local','dow','week','year_number_sun','predictedrate','actual_rate','plannedrate','rate_defect_type']]

In [5]:
df_needed.head()

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,year_number_sun,predictedrate,actual_rate,plannedrate,rate_defect_type
0,Night,2026-02-14T00:00:00.000Z,PICK_MANUAL,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,278,47.983164,100.0,under_performance
1,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM2,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,330,458.315428,231.0,over_performance
2,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAM,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,431,454.370016,350.0,over_performance
3,Night,2026-02-14T00:00:00.000Z,PPSINGLENOSLAMMIX,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,239,307.107182,266.0,over_performance
4,Night,2026-02-14T00:00:00.000Z,PPAFE1INDUCT,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,1324,1484.747996,1235.0,over_performance

In [6]:
df_needed['process_path'].value_counts()

process_path
PPSINGLENOSLAM       213
PPSINGLENOSLAM2      193
PICK_MANUAL          186
PPAFE1INDUCT         131
PPSINGLENOSLAMMIX    114
PPSINGLEMEDIUM        97
PPAFE1PACK            74
PPPICKTOREBIN4        67
PPPICKTOREBIN2        58
PPPICKTOREBIN3        54
PICK_AR               40
PPMULTIST              1
Name: count, dtype: int64

In [7]:
df_needed = df_needed[df_needed['process_path'].isin(['PPAFE1INDUCT', 'PPSINGLEMEDIUM', 'PPAFE1PACK', 'PPPICKTOREBIN2'])]

In [8]:
df_needed['day'] = df_needed['day'].str.rstrip("T00:00:00.000Z")

df_needed.head()

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,year_number_sun,predictedrate,actual_rate,plannedrate,rate_defect_type
4,Night,2026-02-14,PPAFE1INDUCT,2026-02-15T02:00:00.000Z,2026-02-15T05:00:00.000Z,Sun,8,2026,1324,1484.747996,1235.0,over_performance
6,Night,2026-02-14,PPAFE1PACK,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,7,2026,273,306.562894,263.0,over_performance
10,Night,2026-02-14,PPAFE1INDUCT,2026-02-14T23:30:00.000Z,2026-02-15T01:30:00.000Z,Sat,7,2026,1324,1591.983518,1261.0,over_performance
12,Night,2026-02-14,PPAFE1INDUCT,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,7,2026,1391,1500.522809,1261.0,over_performance
13,Night,2026-02-14,PPAFE1PACK,2026-02-14T22:00:00.000Z,2026-02-14T23:30:00.000Z,Sat,7,2026,314,337.638763,263.0,over_performance

In [9]:
df_needed['interval_start_local'] = df_needed['interval_start_local'].str.replace('T',' ')
df_needed['interval_start_local'] = df_needed['interval_start_local'].str.replace('Z','')
df_needed['interval_end_local'] = df_needed['interval_end_local'].str.replace('T',' ')
df_needed['interval_end_local'] = df_needed['interval_end_local'].str.replace('Z','')


df_needed.head(10)

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,year_number_sun,predictedrate,actual_rate,plannedrate,rate_defect_type
4,Night,2026-02-14,PPAFE1INDUCT,2026-02-15 02:00:00.000,2026-02-15 05:00:00.000,Sun,8,2026,1324,1484.747996,1235.0,over_performance
6,Night,2026-02-14,PPAFE1PACK,2026-02-14 23:30:00.000,2026-02-15 01:30:00.000,Sat,7,2026,273,306.562894,263.0,over_performance
10,Night,2026-02-14,PPAFE1INDUCT,2026-02-14 23:30:00.000,2026-02-15 01:30:00.000,Sat,7,2026,1324,1591.983518,1261.0,over_performance
12,Night,2026-02-14,PPAFE1INDUCT,2026-02-14 22:00:00.000,2026-02-14 23:30:00.000,Sat,7,2026,1391,1500.522809,1261.0,over_performance
13,Night,2026-02-14,PPAFE1PACK,2026-02-14 22:00:00.000,2026-02-14 23:30:00.000,Sat,7,2026,314,337.638763,263.0,over_performance
17,Night,2026-02-14,PPAFE1PACK,2026-02-14 19:30:00.000,2026-02-14 21:30:00.000,Sat,7,2026,300,336.950407,280.0,over_performance
18,Night,2026-02-14,PPAFE1INDUCT,2026-02-14 19:30:00.000,2026-02-14 21:30:00.000,Sat,7,2026,1391,1524.073358,1300.0,over_performance
19,Night,2026-02-14,PPAFE1PACK,2026-02-14 18:45:00.000,2026-02-14 19:30:00.000,Sat,7,2026,289,343.903969,280.0,over_performance
21,Night,2026-02-14,PPAFE1INDUCT,2026-02-14 18:45:00.000,2026-02-14 19:30:00.000,Sat,7,2026,1431,1760.000000,1300.0,over_performance
23,Night,2026-02-14,PPPICKTOREBIN2,2026-02-14 18:45:00.000,2026-02-14 19:30:00.000,Sat,7,2026,261,258.887381,225.0,over_performance

In [10]:
df_needed['interval_end_local'] = pd.to_datetime(df_needed['interval_end_local'])
df_needed['interval_start_local'] = pd.to_datetime(df_needed['interval_start_local'])
df_needed['day'] = pd.to_datetime(df_needed['day'])

df_needed.dtypes

shift                           object
day                     datetime64[ns]
process_path                    object
interval_start_local    datetime64[ns]
interval_end_local      datetime64[ns]
dow                             object
week                             int64
year_number_sun                  int64
predictedrate                    int64
actual_rate                    float64
plannedrate                    float64
rate_defect_type                object
dtype: object

In [11]:
df_needed = df_needed.sort_values(by = ['shift','interval_start_local','interval_end_local', 'dow'])

In [12]:
df_needed['day'] = df_needed['interval_start_local'].dt.date
df_needed['interval_start_local'] = df_needed['interval_start_local'].dt.time
df_needed['interval_end_local'] = df_needed['interval_end_local'].dt.time

df_needed.head(10)

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,year_number_sun,predictedrate,actual_rate,plannedrate,rate_defect_type
1226,Day,2026-01-21,PPAFE1INDUCT,08:00:00,09:00:00,Wed,4,2026,1371,1455.955679,1105.0,over_performance
1227,Day,2026-01-21,PPSINGLEMEDIUM,08:00:00,09:00:00,Wed,4,2026,128,126.899812,107.0,over_performance
1220,Day,2026-01-21,PPAFE1INDUCT,09:00:00,10:00:00,Wed,4,2026,1371,1419.765287,1105.0,over_performance
1222,Day,2026-01-21,PPSINGLEMEDIUM,09:00:00,10:00:00,Wed,4,2026,126,139.839119,107.0,over_performance
1211,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,2026,311,330.216002,228.0,over_performance
1214,Day,2026-01-21,PPSINGLEMEDIUM,10:30:00,14:30:00,Wed,4,2026,123,125.085195,104.0,over_performance
1216,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,2026,311,330.216002,228.0,over_performance
1217,Day,2026-01-21,PPAFE1INDUCT,10:30:00,14:30:00,Wed,4,2026,1358,1331.523676,1072.0,over_performance
1204,Day,2026-01-21,PPAFE1PACK,15:00:00,17:00:00,Wed,4,2026,302,267.526725,228.0,over_performance
1206,Day,2026-01-21,PPPICKTOREBIN2,15:00:00,17:00:00,Wed,4,2026,196,230.237673,194.0,over_performance

In [13]:
df_needed = df_needed.drop(columns="year_number_sun")

In [14]:
df_needed['shift'] = df_needed['shift'].str.strip()

In [15]:
df_needed['shift'].str.len()

1226    3
1227    3
1220    3
1222    3
1211    3
       ..
12      5
13      5
6       5
10      5
4       5
Name: shift, Length: 360, dtype: int64

In [16]:
df_ds = df_needed[df_needed['shift'] == 'Day']
df_ns = df_needed[df_needed['shift'] == 'Night']

In [17]:
df_ds

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type
1226,Day,2026-01-21,PPAFE1INDUCT,08:00:00,09:00:00,Wed,4,1371,1455.955679,1105.0,over_performance
1227,Day,2026-01-21,PPSINGLEMEDIUM,08:00:00,09:00:00,Wed,4,128,126.899812,107.0,over_performance
1220,Day,2026-01-21,PPAFE1INDUCT,09:00:00,10:00:00,Wed,4,1371,1419.765287,1105.0,over_performance
1222,Day,2026-01-21,PPSINGLEMEDIUM,09:00:00,10:00:00,Wed,4,126,139.839119,107.0,over_performance
1211,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,311,330.216002,228.0,over_performance
...,...,...,...,...,...,...,...,...,...,...,...
30,Day,2026-02-14,PPPICKTOREBIN2,15:00:00,17:00:00,Sat,7,197,163.320003,202.0,under_performance
31,Day,2026-02-14,PPAFE1INDUCT,15:00:00,17:00:00,Sat,7,1316,1419.785720,1040.0,over_performance
33,Day,2026-02-14,PPSINGLEMEDIUM,15:00:00,17:00:00,Sat,7,159,156.195244,107.0,over_performance
27,Day,2026-02-14,PPSINGLEMEDIUM,17:00:00,18:15:00,Sat,7,142,158.935479,105.0,over_performance
28,Day,2026-02-14,PPAFE1INDUCT,17:00:00,18:15:00,Sat,7,1188,1447.305010,995.0,over_performance

In [18]:
df_ns

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type
1194,Night,2026-01-21,PPAFE1PACK,18:45:00,19:30:00,Wed,4,244,325.803831,270.0,over_performance
1195,Night,2026-01-21,PPAFE1INDUCT,18:45:00,19:30:00,Wed,4,1404,1800.000000,1350.0,over_performance
1184,Night,2026-01-21,PPAFE1PACK,19:30:00,21:30:00,Wed,4,263,332.935891,270.0,over_performance
1187,Night,2026-01-21,PPSINGLEMEDIUM,19:30:00,21:30:00,Wed,4,137,187.003165,150.0,over_performance
1174,Night,2026-01-21,PPAFE1PACK,22:00:00,23:30:00,Wed,4,273,333.340316,254.0,over_performance
...,...,...,...,...,...,...,...,...,...,...,...
12,Night,2026-02-14,PPAFE1INDUCT,22:00:00,23:30:00,Sat,7,1391,1500.522809,1261.0,over_performance
13,Night,2026-02-14,PPAFE1PACK,22:00:00,23:30:00,Sat,7,314,337.638763,263.0,over_performance
6,Night,2026-02-14,PPAFE1PACK,23:30:00,01:30:00,Sat,7,273,306.562894,263.0,over_performance
10,Night,2026-02-14,PPAFE1INDUCT,23:30:00,01:30:00,Sat,7,1324,1591.983518,1261.0,over_performance
4,Night,2026-02-15,PPAFE1INDUCT,02:00:00,05:00:00,Sun,8,1324,1484.747996,1235.0,over_performance

In [19]:
def assign_shift(dow):
    if hasattr(dow, 'strftime'):
        dow = dow.strftime('%A')
    day = dow.strip().title()  
    
    front_end = ['Sun', 'Mon', 'Tue']
    back_end = ['Thu', 'Fri', 'Sat']

    if day in front_end:
        return'Front End'
    elif day in back_end:
        return 'Back End'
    elif day == 'Wed':
        return 'Double Shift'
    else:
        return 'unknown'

In [20]:
df_ds['fe_be'] = df_ds['dow'].apply(assign_shift)
df_ns['fe_be'] = df_ns['dow'].apply(assign_shift)

C:\Users\aboyadec\AppData\Local\Temp\ipykernel_10496\317559814.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ds['fe_be'] = df_ds['dow'].apply(assign_shift)
C:\Users\aboyadec\AppData\Local\Temp\ipykernel_10496\317559814.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ns['fe_be'] = df_ns['dow'].apply(assign_shift)

In [21]:
df_ns

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type,fe_be
1194,Night,2026-01-21,PPAFE1PACK,18:45:00,19:30:00,Wed,4,244,325.803831,270.0,over_performance,Double Shift
1195,Night,2026-01-21,PPAFE1INDUCT,18:45:00,19:30:00,Wed,4,1404,1800.000000,1350.0,over_performance,Double Shift
1184,Night,2026-01-21,PPAFE1PACK,19:30:00,21:30:00,Wed,4,263,332.935891,270.0,over_performance,Double Shift
1187,Night,2026-01-21,PPSINGLEMEDIUM,19:30:00,21:30:00,Wed,4,137,187.003165,150.0,over_performance,Double Shift
1174,Night,2026-01-21,PPAFE1PACK,22:00:00,23:30:00,Wed,4,273,333.340316,254.0,over_performance,Double Shift
...,...,...,...,...,...,...,...,...,...,...,...,...
12,Night,2026-02-14,PPAFE1INDUCT,22:00:00,23:30:00,Sat,7,1391,1500.522809,1261.0,over_performance,Back End
13,Night,2026-02-14,PPAFE1PACK,22:00:00,23:30:00,Sat,7,314,337.638763,263.0,over_performance,Back End
6,Night,2026-02-14,PPAFE1PACK,23:30:00,01:30:00,Sat,7,273,306.562894,263.0,over_performance,Back End
10,Night,2026-02-14,PPAFE1INDUCT,23:30:00,01:30:00,Sat,7,1324,1591.983518,1261.0,over_performance,Back End
4,Night,2026-02-15,PPAFE1INDUCT,02:00:00,05:00:00,Sun,8,1324,1484.747996,1235.0,over_performance,Front End

In [22]:
df_ds

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type,fe_be
1226,Day,2026-01-21,PPAFE1INDUCT,08:00:00,09:00:00,Wed,4,1371,1455.955679,1105.0,over_performance,Double Shift
1227,Day,2026-01-21,PPSINGLEMEDIUM,08:00:00,09:00:00,Wed,4,128,126.899812,107.0,over_performance,Double Shift
1220,Day,2026-01-21,PPAFE1INDUCT,09:00:00,10:00:00,Wed,4,1371,1419.765287,1105.0,over_performance,Double Shift
1222,Day,2026-01-21,PPSINGLEMEDIUM,09:00:00,10:00:00,Wed,4,126,139.839119,107.0,over_performance,Double Shift
1211,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,311,330.216002,228.0,over_performance,Double Shift
...,...,...,...,...,...,...,...,...,...,...,...,...
30,Day,2026-02-14,PPPICKTOREBIN2,15:00:00,17:00:00,Sat,7,197,163.320003,202.0,under_performance,Back End
31,Day,2026-02-14,PPAFE1INDUCT,15:00:00,17:00:00,Sat,7,1316,1419.785720,1040.0,over_performance,Back End
33,Day,2026-02-14,PPSINGLEMEDIUM,15:00:00,17:00:00,Sat,7,159,156.195244,107.0,over_performance,Back End
27,Day,2026-02-14,PPSINGLEMEDIUM,17:00:00,18:15:00,Sat,7,142,158.935479,105.0,over_performance,Back End
28,Day,2026-02-14,PPAFE1INDUCT,17:00:00,18:15:00,Sat,7,1188,1447.305010,995.0,over_performance,Back End

In [23]:
df_needed['fe_be'] = df_needed['dow'].apply(assign_shift)

In [24]:
df_needed.head(50)

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type,fe_be
1226,Day,2026-01-21,PPAFE1INDUCT,08:00:00,09:00:00,Wed,4,1371,1455.955679,1105.0,over_performance,Double Shift
1227,Day,2026-01-21,PPSINGLEMEDIUM,08:00:00,09:00:00,Wed,4,128,126.899812,107.0,over_performance,Double Shift
1220,Day,2026-01-21,PPAFE1INDUCT,09:00:00,10:00:00,Wed,4,1371,1419.765287,1105.0,over_performance,Double Shift
1222,Day,2026-01-21,PPSINGLEMEDIUM,09:00:00,10:00:00,Wed,4,126,139.839119,107.0,over_performance,Double Shift
1211,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,311,330.216002,228.0,over_performance,Double Shift
1214,Day,2026-01-21,PPSINGLEMEDIUM,10:30:00,14:30:00,Wed,4,123,125.085195,104.0,over_performance,Double Shift
1216,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,311,330.216002,228.0,over_performance,Double Shift
1217,Day,2026-01-21,PPAFE1INDUCT,10:30:00,14:30:00,Wed,4,1358,1331.523676,1072.0,over_performance,Double Shift
1204,Day,2026-01-21,PPAFE1PACK,15:00:00,17:00:00,Wed,4,302,267.526725,228.0,over_performance,Double Shift
1206,Day,2026-01-21,PPPICKTOREBIN2,15:00:00,17:00:00,Wed,4,196,230.237673,194.0,over_performance,Double Shift
1208,Day,2026-01-21,PPAFE1INDUCT,15:00:00,17:00:00,Wed,4,1345,1532.119309,1040.0,over_performance,Double Shift
1200,Day,2026-01-21,PPAFE1INDUCT,17:00:00,18:15:00,Wed,4,1252,1396.684250,995.0,over_performance,Double Shift
1201,Day,2026-01-21,PPAFE1PACK,17:00:00,18:15:00,Wed,4,275,263.711030,212.0,over_performance,Double Shift
1203,Day,2026-01-21,PPPICKTOREBIN2,17:00:00,18:15:00,Wed,4,183,220.298914,180.0,over_performance,Double Shift
1155,Day,2026-01-22,PPPICKTOREBIN2,08:00:00,09:00:00,Thu,4,209,159.027803,205.0,under_performance,Back End
1156,Day,2026-01-22,PPAFE1INDUCT,08:00:00,09:00:00,Thu,4,1299,1427.328456,1105.0,over_performance,Back End
1152,Day,2026-01-22,PPPICKTOREBIN2,09:00:00,10:00:00,Thu,4,199,157.454650,205.0,under_performance,Back End
1153,Day,2026-01-22,PPAFE1PACK,09:00:00,10:00:00,Thu,4,292,276.283001,225.0,over_performance,Back End
1147,Day,2026-01-22,PPAFE1INDUCT,10:30:00,14:30:00,Thu,4,1287,1385.170630,1072.0,over_performance,Back End
1148,Day,2026-01-22,PPAFE1PACK,10:30:00,14:30:00,Thu,4,297,278.448786,218.0,over_performance,Back End
1149,Day,2026-01-22,PPAFE1PACK,10:30:00,14:30:00,Thu,4,297,278.448786,218.0,over_performance,Back End
1140,Day,2026-01-22,PPAFE1INDUCT,15:00:00,17:00:00,Thu,4,1299,1313.108551,1072.0,over_performance,Back End
1135,Day,2026-01-22,PPSINGLEMEDIUM,17:00:00,18:15:00,Thu,4,115,82.115840,120.0,under_performance,Back End
1137,Day,2026-01-22,PPAFE1INDUCT,17:00:00,18:15:00,Thu,4,1186,1307.656613,1042.0,over_performance,Back End
1102,Day,2026-01-23,PPSINGLEMEDIUM,08:00:00,09:00:00,Fri,4,147,97.819643,128.0,under_performance,Back End
1099,Day,2026-01-23,PPAFE1PACK,09:00:00,10:00:00,Fri,4,227,324.723365,218.0,over_performance,Back End
1100,Day,2026-01-23,PPAFE1INDUCT,09:00:00,10:00:00,Fri,4,1219,1329.447115,1072.0,over_performance,Back End
1091,Day,2026-01-23,PPAFE1INDUCT,10:30:00,14:30:00,Fri,4,1207,1261.524418,1040.0,over_performance,Back End
1093,Day,2026-01-23,PPAFE1PACK,10:30:00,14:30:00,Fri,4,232,301.213335,218.0,over_performance,Back End
1089,Day,2026-01-23,PPAFE1INDUCT,15:00:00,17:00:00,Fri,4,1207,1380.121315,995.0,over_performance,Back End
1056,Day,2026-01-24,PPAFE1PACK,08:00:00,09:00:00,Sat,4,248,285.877695,NaN,over_performance,Back End
1047,Day,2026-01-24,PPAFE1PACK,09:00:00,10:00:00,Sat,4,228,268.862332,NaN,over_performance,Back End
1049,Day,2026-01-24,PPAFE1INDUCT,09:00:00,10:00:00,Sat,4,1196,1401.111994,NaN,over_performance,Back End
1051,Day,2026-01-24,PPPICKTOREBIN2,09:00:00,10:00:00,Sat,4,190,243.508169,NaN,over_performance,Back End
1043,Day,2026-01-24,PPPICKTOREBIN2,10:30:00,14:30:00,Sat,4,194,223.328365,NaN,over_performance,Back End
1044,Day,2026-01-24,PPAFE1INDUCT,10:30:00,14:30:00,Sat,4,1185,1391.030133,NaN,over_performance,Back End
1032,Day,2026-01-24,PPAFE1INDUCT,15:00:00,17:00:00,Sat,4,1185,1430.015848,NaN,over_performance,Back End
1034,Day,2026-01-24,PPPICKTOREBIN2,15:00:00,17:00:00,Sat,4,190,218.606399,NaN,over_performance,Back End
1036,Day,2026-01-24,PPAFE1PACK,15:00:00,17:00:00,Sat,4,223,256.667916,NaN,over_performance,Back End
1023,Day,2026-01-24,PPAFE1INDUCT,17:00:00,18:15:00,Sat,4,1092,1335.674157,NaN,over_performance,Back End
1028,Day,2026-01-24,PPAFE1PACK,17:00:00,18:15:00,Sat,4,201,273.949011,NaN,over_performance,Back End
1029,Day,2026-01-24,PPSINGLEMEDIUM,17:00:00,18:15:00,Sat,4,119,144.163823,NaN,over_performance,Back End
1030,Day,2026-01-24,PPPICKTOREBIN2,17:00:00,18:15:00,Sat,4,177,204.898344,NaN,over_performance,Back End
995,Day,2026-01-25,PPPICKTOREBIN2,08:00:00,09:00:00,Sun,5,225,149.578824,205.0,under_performance,Front End
996,Day,2026-01-25,PPAFE1INDUCT,08:00:00,09:00:00,Sun,5,1297,1312.482066,1105.0,over_performance,Front End
988,Day,2026-01-25,PPSINGLEMEDIUM,09:00:00,10:00:00,Sun,5,138,107.830121,145.0,under_performance,Front End
991,Day,2026-01-25,PPAFE1INDUCT,09:00:00,10:00:00,Sun,5,1310,1365.458015,1105.0,over_performance,Front End
992,Day,2026-01-25,PPPICKTOREBIN2,09:00:00,10:00:00,Sun,5,223,170.198046,205.0,under_performance,Front End
982,Day,2026-01-25,PPAFE1INDUCT,10:30:00,14:30:00,Sun,5,1297,1324.536731,1072.0,over_performance,Front End
986,Day,2026-01-25,PPSINGLEMEDIUM,10:30:00,14:30:00,Sun,5,132,95.319315,142.0,under_performance,Front End

In [25]:
df_cleaned = df_needed[df_needed['plannedrate'] != 'null']

In [26]:
cleaned_ds = df_ds[df_ds['plannedrate'] != 'null']
cleaned_ns = df_ns[df_ns['plannedrate'] != 'null']

In [27]:
cleaned_ds

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type,fe_be
1226,Day,2026-01-21,PPAFE1INDUCT,08:00:00,09:00:00,Wed,4,1371,1455.955679,1105.0,over_performance,Double Shift
1227,Day,2026-01-21,PPSINGLEMEDIUM,08:00:00,09:00:00,Wed,4,128,126.899812,107.0,over_performance,Double Shift
1220,Day,2026-01-21,PPAFE1INDUCT,09:00:00,10:00:00,Wed,4,1371,1419.765287,1105.0,over_performance,Double Shift
1222,Day,2026-01-21,PPSINGLEMEDIUM,09:00:00,10:00:00,Wed,4,126,139.839119,107.0,over_performance,Double Shift
1211,Day,2026-01-21,PPAFE1PACK,10:30:00,14:30:00,Wed,4,311,330.216002,228.0,over_performance,Double Shift
...,...,...,...,...,...,...,...,...,...,...,...,...
30,Day,2026-02-14,PPPICKTOREBIN2,15:00:00,17:00:00,Sat,7,197,163.320003,202.0,under_performance,Back End
31,Day,2026-02-14,PPAFE1INDUCT,15:00:00,17:00:00,Sat,7,1316,1419.785720,1040.0,over_performance,Back End
33,Day,2026-02-14,PPSINGLEMEDIUM,15:00:00,17:00:00,Sat,7,159,156.195244,107.0,over_performance,Back End
27,Day,2026-02-14,PPSINGLEMEDIUM,17:00:00,18:15:00,Sat,7,142,158.935479,105.0,over_performance,Back End
28,Day,2026-02-14,PPAFE1INDUCT,17:00:00,18:15:00,Sat,7,1188,1447.305010,995.0,over_performance,Back End

In [28]:
cleaned_ns

,shift,day,process_path,interval_start_local,interval_end_local,dow,week,predictedrate,actual_rate,plannedrate,rate_defect_type,fe_be
1194,Night,2026-01-21,PPAFE1PACK,18:45:00,19:30:00,Wed,4,244,325.803831,270.0,over_performance,Double Shift
1195,Night,2026-01-21,PPAFE1INDUCT,18:45:00,19:30:00,Wed,4,1404,1800.000000,1350.0,over_performance,Double Shift
1184,Night,2026-01-21,PPAFE1PACK,19:30:00,21:30:00,Wed,4,263,332.935891,270.0,over_performance,Double Shift
1187,Night,2026-01-21,PPSINGLEMEDIUM,19:30:00,21:30:00,Wed,4,137,187.003165,150.0,over_performance,Double Shift
1174,Night,2026-01-21,PPAFE1PACK,22:00:00,23:30:00,Wed,4,273,333.340316,254.0,over_performance,Double Shift
...,...,...,...,...,...,...,...,...,...,...,...,...
12,Night,2026-02-14,PPAFE1INDUCT,22:00:00,23:30:00,Sat,7,1391,1500.522809,1261.0,over_performance,Back End
13,Night,2026-02-14,PPAFE1PACK,22:00:00,23:30:00,Sat,7,314,337.638763,263.0,over_performance,Back End
6,Night,2026-02-14,PPAFE1PACK,23:30:00,01:30:00,Sat,7,273,306.562894,263.0,over_performance,Back End
10,Night,2026-02-14,PPAFE1INDUCT,23:30:00,01:30:00,Sat,7,1324,1591.983518,1261.0,over_performance,Back End
4,Night,2026-02-15,PPAFE1INDUCT,02:00:00,05:00:00,Sun,8,1324,1484.747996,1235.0,over_performance,Front End

In [29]:
df_summary = df_cleaned.groupby(['process_path','fe_be', 'shift','interval_start_local', 'interval_end_local']).agg({'predictedrate':'mean','actual_rate': 'mean','plannedrate':'mean'}).reset_index().round(3)
df_summary.head(40)

,process_path,fe_be,shift,interval_start_local,interval_end_local,predictedrate,actual_rate,plannedrate
0,PPAFE1INDUCT,Back End,Day,08:00:00,09:00:00,1273.667,1407.851,1105.000
1,PPAFE1INDUCT,Back End,Day,09:00:00,10:00:00,1227.857,1399.662,1099.500
2,PPAFE1INDUCT,Back End,Day,10:30:00,14:30:00,1238.375,1338.695,1067.429
3,PPAFE1INDUCT,Back End,Day,15:00:00,17:00:00,1246.000,1385.241,1038.143
4,PPAFE1INDUCT,Back End,Day,17:00:00,18:15:00,1131.889,1324.772,1002.833
5,PPAFE1INDUCT,Back End,Night,02:00:00,05:00:00,1281.600,1284.876,1263.600
6,PPAFE1INDUCT,Back End,Night,18:45:00,19:30:00,1460.000,1589.779,1291.667
7,PPAFE1INDUCT,Back End,Night,19:30:00,21:30:00,1422.000,1546.242,1300.000
8,PPAFE1INDUCT,Back End,Night,22:00:00,23:30:00,1373.143,1598.992,1268.000
9,PPAFE1INDUCT,Back End,Night,23:30:00,01:30:00,1329.000,1583.581,1261.000
10,PPAFE1INDUCT,Double Shift,Day,08:00:00,09:00:00,1300.750,1168.428,1107.500
11,PPAFE1INDUCT,Double Shift,Day,09:00:00,10:00:00,1290.333,1473.204,1097.333
12,PPAFE1INDUCT,Double Shift,Day,10:30:00,14:30:00,1306.500,1380.414,1074.500
13,PPAFE1INDUCT,Double Shift,Day,15:00:00,17:00:00,1306.500,1456.898,817.250
14,PPAFE1INDUCT,Double Shift,Day,17:00:00,18:15:00,1253.750,1321.958,997.250
15,PPAFE1INDUCT,Double Shift,Night,18:45:00,19:30:00,1346.500,1732.328,1375.000
16,PPAFE1INDUCT,Double Shift,Night,22:00:00,23:30:00,1340.500,1245.593,1334.000
17,PPAFE1INDUCT,Front End,Day,08:00:00,09:00:00,1272.600,1398.467,1109.000
18,PPAFE1INDUCT,Front End,Day,09:00:00,10:00:00,1282.750,1435.240,1107.500
19,PPAFE1INDUCT,Front End,Day,10:30:00,14:30:00,1288.429,1358.619,1074.857
20,PPAFE1INDUCT,Front End,Day,15:00:00,17:00:00,1290.625,1391.716,1042.571
21,PPAFE1INDUCT,Front End,Day,17:00:00,18:15:00,1188.833,1272.055,996.500
22,PPAFE1INDUCT,Front End,Night,02:00:00,05:00:00,1306.571,1645.544,1248.714
23,PPAFE1INDUCT,Front End,Night,18:45:00,19:30:00,1476.000,1994.150,1333.333
24,PPAFE1INDUCT,Front End,Night,19:30:00,21:30:00,1435.000,1762.206,1333.333
25,PPAFE1INDUCT,Front End,Night,22:00:00,23:30:00,1417.000,1682.405,1309.500
26,PPAFE1INDUCT,Front End,Night,23:30:00,01:30:00,1409.500,1845.686,1334.000
27,PPAFE1PACK,Back End,Day,08:00:00,09:00:00,278.000,238.464,260.000
28,PPAFE1PACK,Back End,Day,09:00:00,10:00:00,247.200,270.209,234.333
29,PPAFE1PACK,Back End,Day,10:30:00,14:30:00,272.750,266.749,226.500
30,PPAFE1PACK,Back End,Day,15:00:00,17:00:00,244.667,251.247,252.000
31,PPAFE1PACK,Back End,Day,17:00:00,18:15:00,227.750,224.762,234.000
32,PPAFE1PACK,Back End,Night,02:00:00,05:00:00,236.714,222.826,248.143
33,PPAFE1PACK,Back End,Night,18:45:00,19:30:00,278.714,302.896,262.143
34,PPAFE1PACK,Back End,Night,19:30:00,21:30:00,266.000,315.251,250.500
35,PPAFE1PACK,Back End,Night,22:00:00,23:30:00,288.500,300.450,243.500
36,PPAFE1PACK,Back End,Night,23:30:00,01:30:00,258.000,254.308,282.000
37,PPAFE1PACK,Double Shift,Day,08:00:00,09:00:00,318.000,79.479,260.000
38,PPAFE1PACK,Double Shift,Day,09:00:00,10:00:00,290.000,211.678,260.000
39,PPAFE1PACK,Double Shift,Day,10:30:00,14:30:00,289.500,314.816,239.500

In [30]:
df_summary['Shift'] = (df_summary['fe_be'] + ' ' + df_summary['shift'])
df_summary.head(10)

,process_path,fe_be,shift,interval_start_local,interval_end_local,predictedrate,actual_rate,plannedrate,Shift
0,PPAFE1INDUCT,Back End,Day,08:00:00,09:00:00,1273.667,1407.851,1105.000,Back End Day
1,PPAFE1INDUCT,Back End,Day,09:00:00,10:00:00,1227.857,1399.662,1099.500,Back End Day
2,PPAFE1INDUCT,Back End,Day,10:30:00,14:30:00,1238.375,1338.695,1067.429,Back End Day
3,PPAFE1INDUCT,Back End,Day,15:00:00,17:00:00,1246.000,1385.241,1038.143,Back End Day
4,PPAFE1INDUCT,Back End,Day,17:00:00,18:15:00,1131.889,1324.772,1002.833,Back End Day
5,PPAFE1INDUCT,Back End,Night,02:00:00,05:00:00,1281.600,1284.876,1263.600,Back End Night
6,PPAFE1INDUCT,Back End,Night,18:45:00,19:30:00,1460.000,1589.779,1291.667,Back End Night
7,PPAFE1INDUCT,Back End,Night,19:30:00,21:30:00,1422.000,1546.242,1300.000,Back End Night
8,PPAFE1INDUCT,Back End,Night,22:00:00,23:30:00,1373.143,1598.992,1268.000,Back End Night
9,PPAFE1INDUCT,Back End,Night,23:30:00,01:30:00,1329.000,1583.581,1261.000,Back End Night

In [31]:
df_summary = df_summary.drop(columns = ['fe_be', 'shift'])

In [32]:
df_summary.head(150)

,process_path,interval_start_local,interval_end_local,predictedrate,actual_rate,plannedrate,Shift
0,PPAFE1INDUCT,08:00:00,09:00:00,1273.667,1407.851,1105.000,Back End Day
1,PPAFE1INDUCT,09:00:00,10:00:00,1227.857,1399.662,1099.500,Back End Day
2,PPAFE1INDUCT,10:30:00,14:30:00,1238.375,1338.695,1067.429,Back End Day
3,PPAFE1INDUCT,15:00:00,17:00:00,1246.000,1385.241,1038.143,Back End Day
4,PPAFE1INDUCT,17:00:00,18:15:00,1131.889,1324.772,1002.833,Back End Day
...,...,...,...,...,...,...,...
98,PPSINGLEMEDIUM,02:00:00,05:00:00,118.750,106.115,121.250,Front End Night
99,PPSINGLEMEDIUM,18:45:00,19:30:00,167.000,127.321,160.000,Front End Night
100,PPSINGLEMEDIUM,19:30:00,21:30:00,159.000,121.593,160.000,Front End Night
101,PPSINGLEMEDIUM,22:00:00,23:30:00,155.000,108.137,136.000,Front End Night
102,PPSINGLEMEDIUM,23:30:00,01:30:00,141.000,104.935,136.000,Front End Night

In [33]:
df_summary['interval_start_local'] = df_summary['interval_start_local'].apply(
    lambda x: x.strftime('%H:%M GMT') if pd.notna(x) else None
)

In [34]:
df_summary['interval_end_local'] = df_summary['interval_end_local'].apply(
    lambda x: x.strftime('%H:%M GMT') if pd.notna(x) else None
)

In [35]:
df_summary

,process_path,interval_start_local,interval_end_local,predictedrate,actual_rate,plannedrate,Shift
0,PPAFE1INDUCT,08:00 GMT,09:00 GMT,1273.667,1407.851,1105.000,Back End Day
1,PPAFE1INDUCT,09:00 GMT,10:00 GMT,1227.857,1399.662,1099.500,Back End Day
2,PPAFE1INDUCT,10:30 GMT,14:30 GMT,1238.375,1338.695,1067.429,Back End Day
3,PPAFE1INDUCT,15:00 GMT,17:00 GMT,1246.000,1385.241,1038.143,Back End Day
4,PPAFE1INDUCT,17:00 GMT,18:15 GMT,1131.889,1324.772,1002.833,Back End Day
...,...,...,...,...,...,...,...
98,PPSINGLEMEDIUM,02:00 GMT,05:00 GMT,118.750,106.115,121.250,Front End Night
99,PPSINGLEMEDIUM,18:45 GMT,19:30 GMT,167.000,127.321,160.000,Front End Night
100,PPSINGLEMEDIUM,19:30 GMT,21:30 GMT,159.000,121.593,160.000,Front End Night
101,PPSINGLEMEDIUM,22:00 GMT,23:30 GMT,155.000,108.137,136.000,Front End Night
102,PPSINGLEMEDIUM,23:30 GMT,01:30 GMT,141.000,104.935,136.000,Front End Night

In [36]:
AFEINDUCT_summary  =  df_summary[df_summary['process_path'] == 'PPAFE1INDUCT']

In [37]:
AFEPACK_summay  =  df_summary[df_summary['process_path'] == 'PPAFE1PACK']
PPPICKTOREBIN2_summary = df_summary[df_summary['process_path'] == 'PPPICKTOREBIN2']
PPSINGLEMEDIUM_summary = df_summary[df_summary['process_path'] == 'PPSINGLEMEDIUM']

In [38]:
AFEINDUCT_summary = AFEINDUCT_summary.sort_values(by='interval_start_local')

In [39]:
AFE_INDUCTTIME = AFEINDUCT_summary.groupby('interval_start_local').agg({'predictedrate':'mean','actual_rate': 'mean','plannedrate':'mean'}).reset_index().round(3)

In [40]:


df_long = AFE_INDUCTTIME.melt(
    id_vars='interval_start_local',
    value_vars=['predictedrate', 'actual_rate', 'plannedrate'],
    var_name='rate_type',
    value_name='rate'
)

fig = px.line(
    df_long,
    x='interval_start_local',
    y='rate',
    color='rate_type',
    markers=True,
    text='rate',
    title='Average Rate Deviation by Time For AFE Induct',
    labels={ 'interval_start_local': 'Average Time Across Shifts',
            'rate': 'Aggregated Rates Across Shift',
            'rate_type': 'Rates Type'}
)
fig.update_traces(textposition='top center')
fig.show()

In [41]:
sm_time = PPSINGLEMEDIUM_summary.groupby('interval_start_local').agg({'predictedrate':'mean','actual_rate': 'mean','plannedrate':'mean'}).reset_index().round(3)

In [42]:
p2r2_time = PPPICKTOREBIN2_summary.groupby('interval_start_local').agg({'predictedrate':'mean','actual_rate': 'mean','plannedrate':'mean'}).reset_index().round(3)
afe_pack = AFEPACK_summay.groupby('interval_start_local').agg({'predictedrate':'mean','actual_rate': 'mean','plannedrate':'mean'}).reset_index().round(3)

In [43]:
p2r2_long = p2r2_time.melt(
    id_vars='interval_start_local',
    value_vars=['predictedrate', 'actual_rate', 'plannedrate'],
    var_name='rate_type',
    value_name='rate'
)

fig = px.line(
    p2r2_long,
    x='interval_start_local',
    y='rate',
    color='rate_type',
    markers=True,
    text='rate',
    title='Average Rate Deviation by Time For Pick To Rebin 2 (PACK)',
    labels={ 'interval_start_local': 'Average Time Across Shifts',
            'rates': 'Aggregated Rates Across Shift',
            'rate_type': 'Rates Type'}
)
fig.update_traces(textposition='top center')
fig.show()

In [44]:
sm_long = sm_time.melt(
    id_vars='interval_start_local',
    value_vars=['predictedrate', 'actual_rate', 'plannedrate'],
    var_name='rate_type',
    value_name='rate'
)

fig = px.line(
    sm_long,
    x='interval_start_local',
    y='rate',
    color='rate_type',
    markers=True,
    text='rate',
    title='Average Rate Deviation by Time For Single Medium',
    labels={ 'interval_start_local': 'Average Time Across Shifts',
            'rates': 'Aggregated Rates Across Shift',
            'rate_type': 'Rates Type'}
)
fig.update_traces(textposition='top center')
fig.show()

In [45]:
afe_pack_long = afe_pack.melt(
    id_vars='interval_start_local',
    value_vars=['predictedrate', 'actual_rate', 'plannedrate'],
    var_name='rate_type',
    value_name='rate'
)

fig = px.line(
    afe_pack_long,
    x='interval_start_local',
    y='rate',
    color='rate_type',
    markers=True,
    text='rate',
    title='Average Rate Deviation by Time For AFE Pack',
    labels={ 'interval_start_local': 'Average Time Across Shifts',
            'rates': 'Aggregated Rates Across Shift',
            'rate_type': 'Rates Type'}
)
fig.update_traces(textposition='top center')
fig.show()

In [46]:
df_summary.head(60)

,process_path,interval_start_local,interval_end_local,predictedrate,actual_rate,plannedrate,Shift
0,PPAFE1INDUCT,08:00 GMT,09:00 GMT,1273.667,1407.851,1105.000,Back End Day
1,PPAFE1INDUCT,09:00 GMT,10:00 GMT,1227.857,1399.662,1099.500,Back End Day
2,PPAFE1INDUCT,10:30 GMT,14:30 GMT,1238.375,1338.695,1067.429,Back End Day
3,PPAFE1INDUCT,15:00 GMT,17:00 GMT,1246.000,1385.241,1038.143,Back End Day
4,PPAFE1INDUCT,17:00 GMT,18:15 GMT,1131.889,1324.772,1002.833,Back End Day
5,PPAFE1INDUCT,02:00 GMT,05:00 GMT,1281.600,1284.876,1263.600,Back End Night
6,PPAFE1INDUCT,18:45 GMT,19:30 GMT,1460.000,1589.779,1291.667,Back End Night
7,PPAFE1INDUCT,19:30 GMT,21:30 GMT,1422.000,1546.242,1300.000,Back End Night
8,PPAFE1INDUCT,22:00 GMT,23:30 GMT,1373.143,1598.992,1268.000,Back End Night
9,PPAFE1INDUCT,23:30 GMT,01:30 GMT,1329.000,1583.581,1261.000,Back End Night
10,PPAFE1INDUCT,08:00 GMT,09:00 GMT,1300.750,1168.428,1107.500,Double Shift Day
11,PPAFE1INDUCT,09:00 GMT,10:00 GMT,1290.333,1473.204,1097.333,Double Shift Day
12,PPAFE1INDUCT,10:30 GMT,14:30 GMT,1306.500,1380.414,1074.500,Double Shift Day
13,PPAFE1INDUCT,15:00 GMT,17:00 GMT,1306.500,1456.898,817.250,Double Shift Day
14,PPAFE1INDUCT,17:00 GMT,18:15 GMT,1253.750,1321.958,997.250,Double Shift Day
15,PPAFE1INDUCT,18:45 GMT,19:30 GMT,1346.500,1732.328,1375.000,Double Shift Night
16,PPAFE1INDUCT,22:00 GMT,23:30 GMT,1340.500,1245.593,1334.000,Double Shift Night
17,PPAFE1INDUCT,08:00 GMT,09:00 GMT,1272.600,1398.467,1109.000,Front End Day
18,PPAFE1INDUCT,09:00 GMT,10:00 GMT,1282.750,1435.240,1107.500,Front End Day
19,PPAFE1INDUCT,10:30 GMT,14:30 GMT,1288.429,1358.619,1074.857,Front End Day
20,PPAFE1INDUCT,15:00 GMT,17:00 GMT,1290.625,1391.716,1042.571,Front End Day
21,PPAFE1INDUCT,17:00 GMT,18:15 GMT,1188.833,1272.055,996.500,Front End Day
22,PPAFE1INDUCT,02:00 GMT,05:00 GMT,1306.571,1645.544,1248.714,Front End Night
23,PPAFE1INDUCT,18:45 GMT,19:30 GMT,1476.000,1994.150,1333.333,Front End Night
24,PPAFE1INDUCT,19:30 GMT,21:30 GMT,1435.000,1762.206,1333.333,Front End Night
25,PPAFE1INDUCT,22:00 GMT,23:30 GMT,1417.000,1682.405,1309.500,Front End Night
26,PPAFE1INDUCT,23:30 GMT,01:30 GMT,1409.500,1845.686,1334.000,Front End Night
27,PPAFE1PACK,08:00 GMT,09:00 GMT,278.000,238.464,260.000,Back End Day
28,PPAFE1PACK,09:00 GMT,10:00 GMT,247.200,270.209,234.333,Back End Day
29,PPAFE1PACK,10:30 GMT,14:30 GMT,272.750,266.749,226.500,Back End Day
30,PPAFE1PACK,15:00 GMT,17:00 GMT,244.667,251.247,252.000,Back End Day
31,PPAFE1PACK,17:00 GMT,18:15 GMT,227.750,224.762,234.000,Back End Day
32,PPAFE1PACK,02:00 GMT,05:00 GMT,236.714,222.826,248.143,Back End Night
33,PPAFE1PACK,18:45 GMT,19:30 GMT,278.714,302.896,262.143,Back End Night
34,PPAFE1PACK,19:30 GMT,21:30 GMT,266.000,315.251,250.500,Back End Night
35,PPAFE1PACK,22:00 GMT,23:30 GMT,288.500,300.450,243.500,Back End Night
36,PPAFE1PACK,23:30 GMT,01:30 GMT,258.000,254.308,282.000,Back End Night
37,PPAFE1PACK,08:00 GMT,09:00 GMT,318.000,79.479,260.000,Double Shift Day
38,PPAFE1PACK,09:00 GMT,10:00 GMT,290.000,211.678,260.000,Double Shift Day
39,PPAFE1PACK,10:30 GMT,14:30 GMT,289.500,314.816,239.500,Double Shift Day
40,PPAFE1PACK,15:00 GMT,17:00 GMT,292.500,294.293,239.000,Double Shift Day
41,PPAFE1PACK,17:00 GMT,18:15 GMT,275.000,263.711,212.000,Double Shift Day
42,PPAFE1PACK,02:00 GMT,05:00 GMT,309.000,212.502,252.000,Double Shift Night
43,PPAFE1PACK,18:45 GMT,19:30 GMT,266.500,324.828,270.000,Double Shift Night
44,PPAFE1PACK,19:30 GMT,21:30 GMT,263.000,332.936,270.000,Double Shift Night
45,PPAFE1PACK,22:00 GMT,23:30 GMT,273.000,333.340,254.000,Double Shift Night
46,PPAFE1PACK,23:30 GMT,01:30 GMT,264.667,245.681,257.000,Double Shift Night
47,PPAFE1PACK,08:00 GMT,09:00 GMT,281.000,221.445,NaN,Front End Day
48,PPAFE1PACK,10:30 GMT,14:30 GMT,312.000,291.568,252.000,Front End Day
49,PPAFE1PACK,15:00 GMT,17:00 GMT,277.000,295.028,250.000,Front End Day
50,PPAFE1PACK,17:00 GMT,18:15 GMT,243.000,273.513,234.000,Front End Day
51,PPAFE1PACK,02:00 GMT,05:00 GMT,262.000,282.010,243.000,Front End Night
52,PPAFE1PACK,18:45 GMT,19:30 GMT,321.000,440.086,260.000,Front End Night
53,PPAFE1PACK,19:30 GMT,21:30 GMT,295.000,339.295,265.000,Front End Night
54,PPAFE1PACK,22:00 GMT,23:30 GMT,298.333,347.726,262.000,Front End Night
55,PPAFE1PACK,23:30 GMT,01:30 GMT,249.000,318.372,259.000,Front End Night
56,PPPICKTOREBIN2,08:00 GMT,09:00 GMT,201.250,156.113,206.500,Back End Day
57,PPPICKTOREBIN2,09:00 GMT,10:00 GMT,191.000,186.657,206.000,Back End Day
58,PPPICKTOREBIN2,10:30 GMT,14:30 GMT,194.000,223.328,NaN,Back End Day
59,PPPICKTOREBIN2,15:00 GMT,17:00 GMT,190.667,201.506,202.000,Back End Day

In [47]:
agg_table=df_summary.groupby(['process_path','Shift']).agg({'predictedrate':'mean','actual_rate':'mean', 'plannedrate':'mean'}).reset_index().round(3)

In [48]:
agg_table['predictedvsactual%dev'] = ((agg_table['predictedrate'] - agg_table['actual_rate'])/agg_table['actual_rate'])*100

In [49]:
agg_table['predictedvsactual%dev'] = agg_table['predictedvsactual%dev'].map('{:.2f}%'.format)
agg_table.head(40)

,process_path,Shift,predictedrate,actual_rate,plannedrate,predictedvsactual%dev
0,PPAFE1INDUCT,Back End Day,1223.558,1371.244,1062.581,-10.77%
1,PPAFE1INDUCT,Back End Night,1373.149,1520.694,1276.853,-9.70%
2,PPAFE1INDUCT,Double Shift Day,1291.567,1360.180,1018.767,-5.04%
3,PPAFE1INDUCT,Double Shift Night,1343.500,1488.961,1354.500,-9.77%
4,PPAFE1INDUCT,Front End Day,1264.647,1371.219,1066.086,-7.77%
5,PPAFE1INDUCT,Front End Night,1408.814,1785.998,1311.776,-21.12%
6,PPAFE1PACK,Back End Day,254.073,250.286,241.367,1.51%
7,PPAFE1PACK,Back End Night,265.586,279.146,257.257,-4.86%
8,PPAFE1PACK,Double Shift Day,293.000,232.795,242.100,25.86%
9,PPAFE1PACK,Double Shift Night,275.233,289.857,260.600,-5.05%
10,PPAFE1PACK,Front End Day,278.250,270.388,245.333,2.91%
11,PPAFE1PACK,Front End Night,285.067,345.498,257.800,-17.49%
12,PPPICKTOREBIN2,Back End Day,189.450,192.828,204.833,-1.75%
13,PPPICKTOREBIN2,Back End Night,220.310,231.421,223.810,-4.80%
14,PPPICKTOREBIN2,Double Shift Day,195.750,169.992,196.750,15.15%
15,PPPICKTOREBIN2,Double Shift Night,212.333,220.552,237.000,-3.73%
16,PPPICKTOREBIN2,Front End Day,205.500,193.982,195.688,5.94%
17,PPPICKTOREBIN2,Front End Night,211.722,188.971,233.056,12.04%
18,PPSINGLEMEDIUM,Back End Day,133.959,132.065,114.219,1.43%
19,PPSINGLEMEDIUM,Back End Night,137.428,137.623,131.261,-0.14%
20,PPSINGLEMEDIUM,Double Shift Day,126.125,126.603,106.562,-0.38%
21,PPSINGLEMEDIUM,Double Shift Night,132.833,156.323,147.000,-15.03%
22,PPSINGLEMEDIUM,Front End Day,118.500,118.521,119.700,-0.02%
23,PPSINGLEMEDIUM,Front End Night,148.150,113.620,142.650,30.39%