In [54]:
import pandas as pd
import numpy as np 
import datetime as dt
import openpyxl
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

In [2]:
brs1 = pd.read_csv("data(26).csv")

In [3]:
brs1.head(10)

,Id,Label=ALPS Capacity [Current: {last}],Label=Override [Current: {last}],Label=Override [Current: {last}].1,Label=Total OB Pack [last: {last}]
0,Label,"ALPS Capacity [Current: 10,320.00]","Override [Current: 9,476.00]",Override [Current: {last}],Total OB Pack [last: 960.00]
1,Result,MetricData,MetricData,NoMetric,MetricData
2,Min,9212,0,NaN,24
3,Avg,17693.62421,2842.8,NaN,16370.06897
4,Max,31700,9476,NaN,32952
5,2026/02/08 07:00 GMT,NaN,NaN,NaN,NaN
6,2026/02/08 07:05 GMT,NaN,NaN,NaN,NaN
7,2026/02/08 07:10 GMT,NaN,NaN,NaN,NaN
8,2026/02/08 07:15 GMT,NaN,NaN,NaN,NaN
9,2026/02/08 07:20 GMT,NaN,NaN,NaN,NaN

In [4]:
brs1_drp = brs1.drop([0,1,2,3,4]).reset_index()
brs1_drp.head(10)

,index,Id,Label=ALPS Capacity [Current: {last}],Label=Override [Current: {last}],Label=Override [Current: {last}].1,Label=Total OB Pack [last: {last}]
0,5,2026/02/08 07:00 GMT,NaN,NaN,NaN,NaN
1,6,2026/02/08 07:05 GMT,NaN,NaN,NaN,NaN
2,7,2026/02/08 07:10 GMT,NaN,NaN,NaN,NaN
3,8,2026/02/08 07:15 GMT,NaN,NaN,NaN,NaN
4,9,2026/02/08 07:20 GMT,NaN,NaN,NaN,NaN
5,10,2026/02/08 07:25 GMT,NaN,NaN,NaN,NaN
6,11,2026/02/08 07:30 GMT,NaN,NaN,NaN,NaN
7,12,2026/02/08 07:35 GMT,NaN,NaN,NaN,NaN
8,13,2026/02/08 07:40 GMT,NaN,NaN,NaN,NaN
9,14,2026/02/08 07:45 GMT,NaN,NaN,NaN,NaN

In [5]:
brs1_clean = brs1_drp.drop(['index'], axis = 1)
brs1_clean.head(20)

,Id,Label=ALPS Capacity [Current: {last}],Label=Override [Current: {last}],Label=Override [Current: {last}].1,Label=Total OB Pack [last: {last}]
0,2026/02/08 07:00 GMT,NaN,NaN,NaN,NaN
1,2026/02/08 07:05 GMT,NaN,NaN,NaN,NaN
2,2026/02/08 07:10 GMT,NaN,NaN,NaN,NaN
3,2026/02/08 07:15 GMT,NaN,NaN,NaN,NaN
4,2026/02/08 07:20 GMT,NaN,NaN,NaN,NaN
5,2026/02/08 07:25 GMT,NaN,NaN,NaN,NaN
6,2026/02/08 07:30 GMT,NaN,NaN,NaN,NaN
7,2026/02/08 07:35 GMT,NaN,NaN,NaN,NaN
8,2026/02/08 07:40 GMT,NaN,NaN,NaN,NaN
9,2026/02/08 07:45 GMT,NaN,NaN,NaN,NaN
10,2026/02/08 07:50 GMT,NaN,NaN,NaN,NaN
11,2026/02/08 07:55 GMT,NaN,NaN,NaN,NaN
12,2026/02/08 08:00 GMT,14822,NaN,NaN,276
13,2026/02/08 08:05 GMT,16485,NaN,NaN,6180
14,2026/02/08 08:10 GMT,16485,NaN,NaN,10920
15,2026/02/08 08:15 GMT,16485,NaN,NaN,8148
16,2026/02/08 08:20 GMT,16485,NaN,NaN,7488
17,2026/02/08 08:25 GMT,16485,NaN,NaN,6792
18,2026/02/08 08:30 GMT,16485,NaN,NaN,7428
19,2026/02/08 08:35 GMT,15190,NaN,NaN,8568

In [6]:
brs1_clean.head(20)

,Id,Label=ALPS Capacity [Current: {last}],Label=Override [Current: {last}],Label=Override [Current: {last}].1,Label=Total OB Pack [last: {last}]
0,2026/02/08 07:00 GMT,NaN,NaN,NaN,NaN
1,2026/02/08 07:05 GMT,NaN,NaN,NaN,NaN
2,2026/02/08 07:10 GMT,NaN,NaN,NaN,NaN
3,2026/02/08 07:15 GMT,NaN,NaN,NaN,NaN
4,2026/02/08 07:20 GMT,NaN,NaN,NaN,NaN
5,2026/02/08 07:25 GMT,NaN,NaN,NaN,NaN
6,2026/02/08 07:30 GMT,NaN,NaN,NaN,NaN
7,2026/02/08 07:35 GMT,NaN,NaN,NaN,NaN
8,2026/02/08 07:40 GMT,NaN,NaN,NaN,NaN
9,2026/02/08 07:45 GMT,NaN,NaN,NaN,NaN
10,2026/02/08 07:50 GMT,NaN,NaN,NaN,NaN
11,2026/02/08 07:55 GMT,NaN,NaN,NaN,NaN
12,2026/02/08 08:00 GMT,14822,NaN,NaN,276
13,2026/02/08 08:05 GMT,16485,NaN,NaN,6180
14,2026/02/08 08:10 GMT,16485,NaN,NaN,10920
15,2026/02/08 08:15 GMT,16485,NaN,NaN,8148
16,2026/02/08 08:20 GMT,16485,NaN,NaN,7488
17,2026/02/08 08:25 GMT,16485,NaN,NaN,6792
18,2026/02/08 08:30 GMT,16485,NaN,NaN,7428
19,2026/02/08 08:35 GMT,15190,NaN,NaN,8568

In [7]:
brs1_clean.shape

(1995, 5)

In [8]:
brs1_clean.describe()

,Id,Label=ALPS Capacity [Current: {last}],Label=Override [Current: {last}],Label=Override [Current: {last}].1,Label=Total OB Pack [last: {last}]
count,1995,1535,10,0,1682
unique,1995,431,2,0,1089
top,2026/02/08 07:00 GMT,18631,0,NaN,144
freq,1,19,7,NaN,7

In [9]:
brs1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 5 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Id                                     1995 non-null   object
 1   Label=ALPS Capacity [Current: {last}]  1535 non-null   object
 2   Label=Override [Current: {last}]       10 non-null     object
 3   Label=Override [Current: {last}].1     0 non-null      object
 4   Label=Total OB Pack [last: {last}]     1682 non-null   object
dtypes: object(5)
memory usage: 78.1+ KB

In [10]:
brs1_clean = brs1_clean.drop(['Label=Override [Current: {last}]', 'Label=Override [Current: {last}].1'], axis=1, errors='ignore')

In [12]:
brs1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 3 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Id                                     1995 non-null   object
 1   Label=ALPS Capacity [Current: {last}]  1535 non-null   object
 2   Label=Total OB Pack [last: {last}]     1682 non-null   object
dtypes: object(3)
memory usage: 46.9+ KB

In [14]:
brs1_clean['Id'] = pd.to_datetime(brs1_clean['Id'])
brs1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 3 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Id                                     1995 non-null   datetime64[ns]
 1   Label=ALPS Capacity [Current: {last}]  1535 non-null   object
 2   Label=Total OB Pack [last: {last}]     1682 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 46.9+ KB

In [19]:
brs1_clean['date_only'] = pd.to_datetime(brs1_clean['Id']).dt.strftime('%Y/%m/%d')
brs1_clean['time_only'] = pd.to_datetime(brs1_clean['Id']).dt.strftime('%H:%M')

brs1_clean.head(250)

,Id,Label=ALPS Capacity [Current: {last}],Label=Total OB Pack [last: {last}],date_only,time_only
0,2026-02-08 07:00:00,NaN,NaN,2026/02/08,07:00
1,2026-02-08 07:05:00,NaN,NaN,2026/02/08,07:05
2,2026-02-08 07:10:00,NaN,NaN,2026/02/08,07:10
3,2026-02-08 07:15:00,NaN,NaN,2026/02/08,07:15
4,2026-02-08 07:20:00,NaN,NaN,2026/02/08,07:20
...,...,...,...,...,...
245,2026-02-09 03:25:00,20630,17268,2026/02/09,03:25
246,2026-02-09 03:30:00,19498,17244,2026/02/09,03:30
247,2026-02-09 03:35:00,19498,16656,2026/02/09,03:35
248,2026-02-09 03:40:00,19102,16452,2026/02/09,03:40
249,2026-02-09 03:45:00,19102,16704,2026/02/09,03:45

In [ ]:
def assign_quarter(time_str):
    # Extract time part
    time_only = time_str.split() if ' ' in time_str else time_str
    hour, minute = map(int, time_only.split(':'))

    # Create time ranges as tuples (start_hour, start_min, end_hour, end_min)
    if (hour == 8 and minute >= 0) or (8 < hour < 10) or (hour == 10 and minute < 35):
        return 'Q1'
    elif (hour == 11 and minute >= 0) or (11 < hour < 14) or (hour == 14 and minute < 35):
        return 'Q2'
    elif (hour == 15 and minute >= 0) or (15 < hour < 18) or (hour == 18 and minute < 35):
        return 'Q3'
    elif (hour == 18 and minute >= 35) or (18 < hour < 20) or (hour == 20 and minute < 5):
        return 'Q1'
    elif (hour == 20 and minute >= 30) or (20 < hour < 24) or (0 <= hour < 1) or (hour == 1 and minute < 50):
        return 'Q2'
    elif (hour == 2 and minute >= 15) or (2 < hour < 5) or (hour == 5 and minute < 5):
        return 'Q3'
    else:
        return 'null'

brs1_clean['Quarter'] = brs1_clean['time_only'].apply(assign_quarter)

In [34]:
brs1_clean.head(250)

,Id,Label=ALPS Capacity [Current: {last}],Label=Total OB Pack [last: {last}],date_only,time_only,Quarter
0,2026-02-08 07:00:00,NaN,NaN,2026/02/08,07:00,null
1,2026-02-08 07:05:00,NaN,NaN,2026/02/08,07:05,null
2,2026-02-08 07:10:00,NaN,NaN,2026/02/08,07:10,null
3,2026-02-08 07:15:00,NaN,NaN,2026/02/08,07:15,null
4,2026-02-08 07:20:00,NaN,NaN,2026/02/08,07:20,null
...,...,...,...,...,...,...
245,2026-02-09 03:25:00,20630,17268,2026/02/09,03:25,Q3
246,2026-02-09 03:30:00,19498,17244,2026/02/09,03:30,Q3
247,2026-02-09 03:35:00,19498,16656,2026/02/09,03:35,Q3
248,2026-02-09 03:40:00,19102,16452,2026/02/09,03:40,Q3
249,2026-02-09 03:45:00,19102,16704,2026/02/09,03:45,Q3

In [35]:
brs1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 6 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Id                                     1995 non-null   datetime64[ns]
 1   Label=ALPS Capacity [Current: {last}]  1535 non-null   object
 2   Label=Total OB Pack [last: {last}]     1682 non-null   object
 3   date_only                              1995 non-null   object
 4   time_only                              1995 non-null   object
 5   Quarter                                1995 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 93.6+ KB

In [39]:

def assign_shift(time_str):
    # Extract time part from "HH:MM GMT" format
    time_only = time_str.split() if ' ' in time_str else time_str
    hour, minute = map(int, time_only.split(':'))

    # Convert to decimal hours for proper comparison
    decimal_time = hour + minute / 60

    # Day Shift: 08:00 to 18:30 (8.0 to 18.5)
    if 8.0 <= decimal_time < 18.5:
        return 'DS'
    # Night Shift: 19:00 to 05:00 (wraps around midnight)
    elif decimal_time >= 19.0 or decimal_time < 5.0:
        return 'NS'
    else:
        return 'null'  # Gap between 18:30 and 19:00

brs1_clean['Shift'] = brs1_clean['time_only'].apply(assign_shift)

In [40]:
brs1_clean.head(300)

,Id,Label=ALPS Capacity [Current: {last}],Label=Total OB Pack [last: {last}],date_only,time_only,Quarter,Shift
0,2026-02-08 07:00:00,NaN,NaN,2026/02/08,07:00,null,null
1,2026-02-08 07:05:00,NaN,NaN,2026/02/08,07:05,null,null
2,2026-02-08 07:10:00,NaN,NaN,2026/02/08,07:10,null,null
3,2026-02-08 07:15:00,NaN,NaN,2026/02/08,07:15,null,null
4,2026-02-08 07:20:00,NaN,NaN,2026/02/08,07:20,null,null
...,...,...,...,...,...,...,...
295,2026-02-09 07:35:00,NaN,NaN,2026/02/09,07:35,null,null
296,2026-02-09 07:40:00,NaN,NaN,2026/02/09,07:40,null,null
297,2026-02-09 07:45:00,NaN,NaN,2026/02/09,07:45,null,null
298,2026-02-09 07:50:00,NaN,NaN,2026/02/09,07:50,null,null
299,2026-02-09 07:55:00,NaN,NaN,2026/02/09,07:55,null,null

In [43]:
brs1_clean_sorted = brs1_clean.sort_values(by=['Quarter', 'Shift'])

brs1_clean_sorted.head(100)

,Id,Label=ALPS Capacity [Current: {last}],Label=Total OB Pack [last: {last}],date_only,time_only,Quarter,Shift
12,2026-02-08 08:00:00,14822,276,2026/02/08,08:00,Q1,DS
13,2026-02-08 08:05:00,16485,6180,2026/02/08,08:05,Q1,DS
14,2026-02-08 08:10:00,16485,10920,2026/02/08,08:10,Q1,DS
15,2026-02-08 08:15:00,16485,8148,2026/02/08,08:15,Q1,DS
16,2026-02-08 08:20:00,16485,7488,2026/02/08,08:20,Q1,DS
...,...,...,...,...,...,...,...
878,2026-02-11 08:10:00,13381,9288,2026/02/11,08:10,Q1,DS
879,2026-02-11 08:15:00,13381,11484,2026/02/11,08:15,Q1,DS
880,2026-02-11 08:20:00,NaN,12156,2026/02/11,08:20,Q1,DS
881,2026-02-11 08:25:00,13381,12240,2026/02/11,08:25,Q1,DS
882,2026-02-11 08:30:00,13381,12864,2026/02/11,08:30,Q1,DS

In [45]:
brs1_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1995 entries, 0 to 1994
Data columns (total 7 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Id                                     1995 non-null   datetime64[ns]
 1   Label=ALPS Capacity [Current: {last}]  1535 non-null   object
 2   Label=Total OB Pack [last: {last}]     1682 non-null   object
 3   date_only                              1995 non-null   object
 4   time_only                              1995 non-null   object
 5   Quarter                                1995 non-null   object
 6   Shift                                  1995 non-null   object
dtypes: datetime64[ns](1), object(6)
memory usage: 109.2+ KB

In [49]:
# Convert the columns to numeric type (handles any non-numeric values)
brs1_clean['Label=ALPS Capacity [Current: {last}]'] = pd.to_numeric(
    brs1_clean['Label=ALPS Capacity [Current: {last}]'],
    errors='coerce'
)
brs1_clean['Label=Total OB Pack [last: {last}]'] = pd.to_numeric(
    brs1_clean['Label=Total OB Pack [last: {last}]'],
    errors='coerce'
)

# Remove rows where Quarter, Shift, or either numeric column has null/NaN values
brs1_clean_filtered = brs1_clean.dropna(subset=[
    'Quarter',
    'Shift',
    'Label=ALPS Capacity [Current: {last}]',
    'Label=Total OB Pack [last: {last}]'
])

# Also exclude rows where Quarter or Shift equals 'null' (as string)
brs1_clean_filtered = brs1_clean_filtered[
    (brs1_clean_filtered['Quarter'] != 'null') &
    (brs1_clean_filtered['Shift'] != 'null')
]

# Now group by Quarter and Shift, calculate averages
summary_table = brs1_clean_filtered.groupby(['Quarter', 'Shift']).agg({
    'Label=ALPS Capacity [Current: {last}]': 'mean',
    'Label=Total OB Pack [last: {last}]': 'mean'
}).reset_index()

# Rename columns for clarity
summary_table.columns = ['Quarter', 'Shift', 'Lagrange Value', 'OB PACK value']

# Round to 2 decimal places
summary_table['Lagrange Value'] = summary_table['Lagrange Value'].round(2)
summary_table['OB PACK value'] = summary_table['OB PACK value'].round(2)

# Calculate % Accuracy (percentage deviation) based on the averaged values
summary_table['% Accuracy'] = (
    (summary_table['OB PACK value'] - summary_table['Lagrange Value'])
    / summary_table['Lagrange Value']
) * 100
summary_table['% Accuracy'] = summary_table['% Accuracy'].round(2)

# Determine Status based on % Accuracy
summary_table['Status'] = np.where(
    abs(summary_table['% Accuracy']) <= 5,
    'Aligned',
    'Not Aligned'
)

# Reorder columns to match your specification
summary_table = summary_table[['Quarter', 'Shift', '% Accuracy', 'Lagrange Value', 'OB PACK value', 'Status']]

# Sort by Quarter and Shift
summary_table = summary_table.sort_values(by=['Quarter', 'Shift'])

summary_table.head()

  Quarter Shift  % Accuracy  Lagrange Value  OB PACK value       Status
0      Q1    DS       -8.55        11962.72       10940.14  Not Aligned
1      Q1    NS       12.94        21479.58       24259.96  Not Aligned
2      Q2    DS        0.29        16631.35       16679.27      Aligned
3      Q2    NS       -2.93        21660.43       21026.08      Aligned
4      Q3    DS       -1.85        18057.83       17723.45      Aligned

In [55]:

# Define the file path (using your preferred location)
file_path = r'C:/Users/aboyadec/Downloads/capacity_summary.xlsx'

# Export to Excel
summary_table.to_excel(file_path, index=False, sheet_name='Summary')

print(f"Summary table exported successfully to: {file_path}")

Summary table exported successfully to: C:/Users/aboyadec/Downloads/capacity_summary.xlsx